name: RemoteFS
options:
  bundleIdPrefix: com.remotefs
  deploymentTarget:
    macOS: "13.0"
  xcodeVersion: "15.0"
  buildDir: .build

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "13.0"

targets:
  RemoteFS:
    type: application
    platform: macOS
    sources:
      - path: RemoteFSMenu
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.remotefs.app
        INFOPLIST_FILE: RemoteFSMenu/Info.plist
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGNING_ALLOWED: NO
        ENABLE_HARDENED_RUNTIME: NO
    preBuildScripts:
      - name: Build Go Binary
        script: |
          cd "$SRCROOT/RemoteFSServer"
          go build -o "$BUILT_PRODUCTS_DIR/remote-fs" .
    postBuildScripts:
      - name: Copy Go Binary
        script: |
          cp "$BUILT_PRODUCTS_DIR/remote-fs" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/MacOS/"
    info:
      path: RemoteFSMenu/Info.plist
      properties:
        CFBundleName: RemoteFS
        CFBundleDisplayName: RemoteFS
        CFBundleIdentifier: com.remotefs.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: RemoteFS
        LSMinimumSystemVersion: "13.0"
        LSUIElement: true
        NSHighResolutionCapable: true
        NSPrincipalClass: NSApplication

schemes:
  RemoteFS:
    build:
      targets:
        RemoteFS: all
    run:
      config: Debug
    archive:
      config: Release
